### ISSUE TITLE
[Layout] pinned 여부에 따른 메모 정렬 

### ISSUE THREAD

**Issue by pyville** [Memo8-KoreaUniv/Kramo#18]

**Comment by SeoSang** [comment]
혹시 진행상황이 어떻게 되나요? 아직 시작 안했다면 제가 한번 구현해봐도 될까요?

**Comment by pyville** [comment]
예전 코드에 적용했던 걸 현재 코드에 맞게 바꾸면 되어서 오늘내일 중으로 할 수 있을 것 같아요~
