### ISSUE TITLE
[카테고리] 카테고리 개수 관련

### ISSUE THREAD

**Issue by SeoSang** [Memo8-KoreaUniv/Kramo#22]
## 문제 인식

API 구현하던 중, 카테고리들을 로드하는 부분에 대해서 페이징 (메모 불러올 때 1페이지, 2페이지 하듯이 하는 페이징)  을 해야하나 생각이 들더군요.

저희 현재 결정된 UI가 카테고리들을 메뉴바에서 나열하는 것이다보니, 카테고리 추가에 제한을 두지 않고 페이징으로 로드하는 것 보다 
카테고리 추가 개수에 제한 개수(약 20개?) 정도를 두고 카테고리가 너무 많아지는 걸 막는 것이 나을 것 같은데 어떻게 생각하시나요?

좋은 의견있으면 부탁드립니다!

**Comment by pyville** [comment]
네 카테고리는 10~20개 정도로 제한해도 될 것 같습니다.
실제로 사용자가 그렇게 많은 카테고리를 관리하려면 카테고리 안에 또다른 카테고리가 있는 nested 카테고리를 만들어야 할 텐데, 
어차피 저희는 해당 기능을 지원하지 않으니까요...

**Comment by SeoSang** [comment]
> 네 카테고리는 10~20개 정도로 제한해도 될 것 같습니다.
> 실제로 사용자가 그렇게 많은 카테고리를 관리하려면 카테고리 안에 또다른 카테고리가 있는 nested 카테고리를 만들어야 할 텐데,
> 어차피 저희는 해당 기능을 지원하지 않으니까요...

넵 저도 그게 좋다고 생각합니다!

**Comment by vwjdtjdwnsv** [comment]
넵 저도 이견 없습니다. 카테고리에 페이징은 필요 없을 것 같아요

**Comment by SeoSang** [comment]
해결 완료 
- 카테고리 개수 20개로 제한 
- 메뉴바에 unnested 한 상태로 리스트
- api 도 페이징 없이 갯수 로드만 지원

**Comment by SeoSang** [comment]
해결 완료

    카테고리 개수 20개로 제한
    메뉴바에 unnested 한 상태로 리스트
    api 도 페이징 없이 갯수 로드만 지원
