### ISSUE TITLE
[Login] 로그인 후 새로고침

### ISSUE THREAD

**Issue by gyunius** [Memo8-KoreaUniv/Kramo#32]
![output1](https://user-images.githubusercontent.com/52598392/121709484-933d0900-cb13-11eb-8450-c99b66c9c967.gif)

로그인에 성공한 뒤 `useRouter.push('/')`을 실행하는데, 좌측 메뉴의 카테고리 목록과 메모 목록(`feature/memo-api`)이 사용자별 목록으로 갱신이 되지 않습니다. 위 영상에서와 마찬가지로 페이지 새로고침 이후에야 반영이 됩니다.

로그아웃도 마찬가지였는데 이 경우는 `onClickLogout()`에 있는 `useRouter.push('/')`를  `useRouter.reload()`로 바꿔서 해결했습니다만, 로그인 쪽은 같은 방법 사용하거나 `reload`를 추가하는 방법으로는 같은 페이지에서 계속 새로고침을 하게 되네요.

해결방법이나 혹시 더 좋은 방법이 있을까 하여 공유드립니다!

**Comment by SeoSang** [comment]
오호 확인했습니다.
저도 한번 대응 방법을 알아보겠습니다!

**Comment by SeoSang** [comment]
@panggyun 해결했습니다! 
useRouter 문제는 아니었고 state 관련 문제더라구요. 
- 로그인 성공 뒤에 따로 유저정보 및 카테고리 state를 로드를 안함 -> 트리거 시키는 로직 추가
- 로그아웃 뒤에  유저정보 및 카테고리 state를  내리는 코드가 없음 -> `me` 와 `categories`를 `null` 및 `[]` 로 바꿈

일단은 의도했던 문제가 아니니 바로 dev에 푸쉬하겠습니다!
