### ISSUE TITLE
[Code] 불필요한 console.log 제거

### ISSUE THREAD

**Issue by pyville** [Memo8-KoreaUniv/Kramo#41]
불필요한 또는 테스트 목적의 console.log를 한번에 제거하는 것이 필요합니다.

**Comment by SeoSang** [comment]
https://github.com/Memo8-KoreaUniv/kramo/issues/8#issue-903608497 

위 이슈랑 중복되는 이슈인 것 같습니다!

**Comment by pyville** [comment]
> [#8 (comment)](https://github.com/Memo8-KoreaUniv/kramo/issues/8#issue-903608497)
> 
> 위 이슈랑 중복되는 이슈인 것 같습니다!

네 이건 일단 close할게요~
